% Допустим, у тебя переменные вида iqr, wm, vds, ... это timeseries
T = table( ...
    iqr.Time, ...              % время возьмём у одной переменной
    idr.Data, ...
    iqr.Data, ...
    wm.Data, ...
    vds.Data, ...
    vqs.Data, ...
    ids.Data, ...
    iqs.Data, ...
    phids.Data, ...
    phiqs.Data, ...
    phidr.Data, ...
    phiqr.Data, ...
    te.Data, ...
    thetam.Data, ...
    vdr.Data, ...
    vqr.Data, ...
    'VariableNames', { ...
        'time','idr','iqr','wm','vds','vqs','ids','iqs', ...
        'phids','phiqs','phidr','phiqr','te','thetam','vdr','vqr' ...
    } ...
);

% Сохраняем в CSV
writetable(T, 'output.csv');
